### PR TITLE
renamed methods to solve the issue #17

### PR DESCRIPTION
**Pull request by marekyggdrasil**
modified:   src/AfterShip/Core/Request.php

### CODE REVIEW

**Comment by marekyggdrasil** [comment]
https://github.com/AfterShip/aftership-sdk-php/issues/17

**Comment by marekyggdrasil** [comment]
https://github.com/AfterShip/team/issues/3541

**Comment by PhilippSchreiber** [comment]
That works perfect. When will it get merged?

**Comment by sunnychow** [comment]
thanks. we merge it now.

**Pull request merged**
